### ISSUE TITLE
Plugin not working with RoundCube devel branch?

### ISSUE THREAD

**Issue by teras** [prodrigestivill/roundcube-gravatar#11]
I tried both, 1.6 and master version of this plugin, but none of them showed any gravatar. Is this plugin not working any more?

**Comment by prodrigestivill** [comment]
Tested with 1.6.4 and it works.

Ensure to enable it in Settings > Preferences > Contacts > Gravatar or enable it globally in roundcube settings.
As explained in [README installation](https://github.com/prodrigestivill/roundcube-gravatar#installation) section.

Don't hesitate to report if any other issue appears with that version.

**Comment by teras** [comment]
I have already enabled this option
![image](https://github.com/prodrigestivill/roundcube-gravatar/assets/592568/4f5e9e25-6f20-4a6e-bfac-836e5fb37515)
But gravater is not working
![image](https://github.com/prodrigestivill/roundcube-gravatar/assets/592568/f27d3ed4-a025-41af-997b-9d35f5dadd49)

So I might consider that this issue shouldn't be closed yet, in a rush :smiley: 
Thank you for your support btw

**Comment by prodrigestivill** [comment]
@teras what theme are you using?
Have you tested using the default theme?

**Comment by teras** [comment]
I haven't changed anything, using the app as is. I am on Debian, installing roundcube from sources.
This is a screenshot in case you find anything interesting.
![image](https://github.com/prodrigestivill/roundcube-gravatar/assets/592568/6d11ac5c-53a7-4a56-9bde-7d67756f406c)

**Comment by prodrigestivill** [comment]
@teras with the current theme (dark or white) the contact image is displayed in the top of the message pane, so there is no image in the message list.

This is a theme decision, so you need to change the theme if you don't like this behaviour.
Can you please confirm the image is not displayed in the top of the message?
Since your screenshots don't cover the place where it is supposed to be in the theme you are using.

**Comment by teras** [comment]
In messages, there is a space for icons, but not gravatar.

I checked on confg, there's no "addressbook" plugin indeed.

I checked on [roundcube plugins](https://github.com/roundcube/roundcubemail/wiki/Plugins) and also [extra plugins](https://plugins.roundcube.net) but there is  no such default plugin and on extras, only an automatic addressbook plugin, google addressbook and nextcloud_sql plugin.

Am I missing something?
Thank you

Attached is an image of a contact (mine) that has gravatar.
![image](https://github.com/prodrigestivill/roundcube-gravatar/assets/592568/5d4549bd-d954-4d77-aa2a-487a4cbdea3e)

**Comment by prodrigestivill** [comment]
Did you ensure this gravatar plugin is always the latest plugin (or at least addressbook plugin) in the `$config['plugins']` list at `config/config.inc.php`?

**Comment by teras** [comment]
Yes it is the latest.
List of plugins:

```
$config['plugins'] = [
        'archive',
        'zipdownload',
        'show_folder_size',
        'managesieve',
        'attachment_reminder',
        'markasjunk',
        'contextmenu',
        'thunderbird_labels',
        'gravatar',
];
```

**Comment by prodrigestivill** [comment]
Hello @teras,

I have tried your set of plugins and your order and it worked, using this versions:

> Roundcube Webmail 1.6.5
> Using version ^0.7.19 for jfcherng-roundcube/show-folder-size
> Using version ^3.3 for johndoh/contextmenu
> Using version ^1.6 for weird-birds/thunderbird_labels
> Using version ^1.6 for prodrigestivill/gravatar

And this order:
```php
$config['plugins'] = [
        'archive',
        'zipdownload',
        'show_folder_size',
        'managesieve',
        'attachment_reminder',
        'markasjunk',
        'contextmenu',
        'thunderbird_labels',
        'gravatar',
];
```

Please **make sure to clear browser cache**, this is important if you changed the gravatar option from disabled to enabled after using roundcube.

**Comment by teras** [comment]
Hello and thank you for your support.

I don't know how, why, or when, but at least for my avatar it works now.

Maybe all the updates and cleaning and all that.

Once more thank you. I think we can close this issue for now!
